name: WP PHPUnit Tests

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk, develop ]

jobs:
  build:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: [ '8.1', '8.2', '8.3', '8.4']
        database: [ 'mysql:5.7', 'mariadb:10.6' ]
    runs-on: ${{ matrix.operating-system }}
    services:
      # Setup MYSQL/MariaDB
      mysql-service:
        image: ${{ matrix.database }}
        env:
          MYSQL_ROOT_PASSWORD: 'poetry'
          MYSQL_DATABASE: wlf_tests
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - name: Setup proper PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.php != '8.1' && 'mbstring' || '' }}
          tools: composer

      - name: Show PHP version
        run: php -v

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer run-script packages-install

      - name: Build Assets
        run: |
          npm install
          npm run build

      - name: Run Tests on Latest Version - WP7.0
        env:
          environment_github: true
        run: composer test:php

